@extends('layouts.app')

@section('title', $product->name.' — চেয়ারঘর')

@section('content')
@vite('resources/css/product.css')
<section class="product-page section">
    <div class="container">
        <nav class="product-breadcrumb" aria-label="breadcrumb"><a href="{{ route('home') }}">হোম</a><i class="bi bi-chevron-right"></i><a href="{{ route('shop') }}">চেয়ার</a><i class="bi bi-chevron-right"></i><span>{{ $product->name }}</span></nav>
        <div class="row g-4 g-xl-5 align-items-start">
            <div class="col-lg-6"><div class="product-gallery-wrap"><div class="product-gallery">@if ($product->sale_price)<span class="product-discount">সাশ্রয় ৳{{ number_format($product->price - $product->sale_price) }}</span>@endif<img src="{{ $product->image }}" alt="{{ $product->name }}" data-product-gallery-main><small><i class="bi bi-arrows-fullscreen"></i> পণ্যের ছবি</small></div>@if ($product->additional_images)<div class="product-gallery-thumbnails"><button class="active" type="button" data-product-gallery-image="{{ $product->image }}" aria-label="প্রধান ছবি দেখুন"><img src="{{ $product->image }}" alt=""></button>@foreach ($product->additional_images as $index => $additionalImage)<button type="button" data-product-gallery-image="{{ $additionalImage }}" aria-label="অতিরিক্ত ছবি {{ $index + 1 }} দেখুন"><img src="{{ $additionalImage }}" alt="" loading="lazy"></button>@endforeach</div>@endif</div></div>
            <div class="col-lg-6"><div class="product-purchase-card">
                <span class="eyebrow">{{ $product->category->name }} · {{ $product->sku }}</span><h1>{{ $product->name }}</h1>
                <div class="product-rating"><span>{{ str_repeat('★', (int) round($product->reviews_avg_rating ?? 0)).str_repeat('☆', 5 - (int) round($product->reviews_avg_rating ?? 0)) }}</span><a href="#productReviews" data-bs-toggle="tab">{{ $product->reviews->count() ? number_format($product->reviews_avg_rating, 1).' · '.$product->reviews->count().'টি রিভিউ' : 'এখনও কোনো রিভিউ নেই' }}</a></div>
                <p class="product-summary">{{ $product->short_description }}</p>
                <div class="product-price-box"><div><small>বর্তমান মূল্য</small><strong>৳{{ number_format($product->current_price) }}</strong></div>@if ($product->sale_price)<del>৳{{ number_format($product->price) }}</del>@endif</div>
                <div class="product-specs"><div><i class="bi bi-layers"></i><span>উপকরণ<b>{{ $product->material ?: 'তথ্য নেই' }}</b></span></div><div><i class="bi bi-palette"></i><span>রং<b>{{ $product->color ?: 'তথ্য নেই' }}</b></span></div><div><i class="bi bi-box-seam"></i><span>স্টক<b class="{{ $product->stock > 0 ? 'text-success' : 'text-danger' }}">{{ $product->stock > 0 ? $product->stock.'টি আছে' : 'স্টক শেষ' }}</b></span></div></div>
                <form method="post" action="{{ route('cart.add', $product) }}" class="product-buy-form">@csrf<label for="productQuantity">পরিমাণ</label><div class="d-flex gap-2"><div class="product-quantity-stepper"><button type="button" data-quantity-decrease aria-label="পরিমাণ কমান"><i class="bi bi-dash-lg"></i></button><input class="form-control" id="productQuantity" type="number" name="quantity" min="1" max="{{ $product->stock }}" value="1" data-quantity-input><button type="button" data-quantity-increase aria-label="পরিমাণ বাড়ান"><i class="bi bi-plus-lg"></i></button></div><button class="btn btn-brand flex-grow-1" @disabled(! $product->stock)><i class="bi bi-bag-plus"></i> কার্টে যোগ করুন</button></div></form>
                <form method="post" action="{{ route('customer.wishlist.add', $product) }}" class="mt-3">@csrf<button class="btn btn-outline-dark" type="submit"><i class="bi bi-heart"></i> উইশলিস্টে রাখুন</button></form>
                <div class="product-assurances"><span><i class="bi bi-truck"></i><b>{{ $siteContent->text('product', 'assurances', 'delivery_title') }}</b><small>{{ $siteContent->text('product', 'assurances', 'delivery_text') }}</small></span><span><i class="bi bi-arrow-repeat"></i><b>{{ $siteContent->text('product', 'assurances', 'returns_title') }}</b><small>{{ $siteContent->text('product', 'assurances', 'returns_text') }}</small></span><span><i class="bi bi-shield-check"></i><b>{{ $siteContent->text('product', 'assurances', 'warranty_title') }}</b><small>{{ $siteContent->text('product', 'assurances', 'warranty_text') }}</small></span></div>
            </div></div>
        </div>
        @php($reviewTabActive = request('tab') === 'reviews' || session()->has('review_success') || $errors->hasAny(['name', 'rating', 'body', 'image']))
        <div class="product-tabs mt-5">
            <ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><button class="nav-link {{ $reviewTabActive ? '' : 'active' }}" data-bs-toggle="tab" data-bs-target="#productDetails" type="button" role="tab"><i class="bi bi-card-text"></i> পণ্যের বিস্তারিত</button></li><li class="nav-item" role="presentation"><button class="nav-link {{ $reviewTabActive ? 'active' : '' }}" data-bs-toggle="tab" data-bs-target="#productReviews" type="button" role="tab"><i class="bi bi-star"></i> রিভিউ <span class="badge">{{ $product->reviews->count() }}</span></button></li></ul>
            <div class="tab-content">
                <div class="tab-pane fade {{ $reviewTabActive ? '' : 'show active' }}" id="productDetails" role="tabpanel" tabindex="0"><div class="row g-4"><div class="col-lg-7"><span class="eyebrow">পণ্য পরিচিতি</span><h2>{{ $product->name }}</h2><p>{{ $product->description ?: $product->short_description }}</p></div><div class="col-lg-5"><div class="details-list"><div><span>ক্যাটাগরি</span><b>{{ $product->category->name }}</b></div><div><span>SKU</span><b>{{ $product->sku }}</b></div><div><span>উপকরণ</span><b>{{ $product->material ?: 'তথ্য নেই' }}</b></div><div><span>রং</span><b>{{ $product->color ?: 'তথ্য নেই' }}</b></div></div></div></div></div>
                <div class="tab-pane fade {{ $reviewTabActive ? 'show active' : '' }}" id="productReviews" role="tabpanel" tabindex="0">
                    <div class="row g-4 g-lg-5">
                        <div class="col-lg-5"><div class="review-form-card"><span class="eyebrow">আপনার মতামত</span><h2>একটি রিভিউ লিখুন</h2><p>লেখার সঙ্গে চাইলে পণ্যের একটি ছবিও যোগ করুন।</p>@if (session('review_success'))<div class="alert alert-success">{{ session('review_success') }}</div>@endif<form method="post" action="{{ route('product.reviews.store', $product) }}" enctype="multipart/form-data">@csrf<div class="mb-3"><label class="form-label" for="reviewName">আপনার নাম *</label><input class="form-control @error('name') is-invalid @enderror" id="reviewName" name="name" value="{{ old('name', auth()->user()?->name) }}" placeholder="আপনার নাম লিখুন" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="mb-3"><label class="form-label" for="reviewRating">রেটিং *</label><select class="form-select @error('rating') is-invalid @enderror" id="reviewRating" name="rating" required><option value="">রেটিং নির্বাচন করুন</option>@foreach ([5 => '★★★★★ অসাধারণ', 4 => '★★★★☆ ভালো', 3 => '★★★☆☆ মোটামুটি', 2 => '★★☆☆☆ খারাপ', 1 => '★☆☆☆☆ খুব খারাপ'] as $value => $label)<option value="{{ $value }}" @selected(old('rating') == $value)>{{ $label }}</option>@endforeach</select>@error('rating')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="mb-3"><label class="form-label" for="reviewBody">আপনার রিভিউ *</label><textarea class="form-control @error('body') is-invalid @enderror" id="reviewBody" name="body" rows="4" placeholder="পণ্যটি ব্যবহার করে আপনার অভিজ্ঞতা লিখুন" required>{{ old('body') }}</textarea>@error('body')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="mb-3"><label class="review-upload" for="reviewImage"><i class="bi bi-image"></i><span><b>ছবি যোগ করুন</b><small>JPG, PNG বা WebP · সর্বোচ্চ ৩ MB</small></span></label><input class="visually-hidden" id="reviewImage" type="file" name="image" accept="image/jpeg,image/png,image/webp">@error('image')<div class="text-danger small mt-1">{{ $message }}</div>@enderror</div><button class="btn btn-brand w-100" type="submit"><i class="bi bi-send"></i> রিভিউ প্রকাশ করুন</button></form></div></div>
                        <div class="col-lg-7"><div class="review-list">@forelse ($product->reviews as $review)<article class="review-item"><div class="review-avatar">{{ mb_substr($review->name, 0, 1) }}</div><div class="review-content"><div class="review-meta"><div><b>{{ $review->name }}</b><span>{{ str_repeat('★', $review->rating).str_repeat('☆', 5 - $review->rating) }}</span></div><small>{{ $review->created_at->format('d M, Y') }}</small></div><p>{{ $review->body }}</p>@if ($review->image_path)<img class="review-photo" src="{{ asset('storage/'.$review->image_path) }}" alt="{{ $review->name }}-এর রিভিউ ছবি">@endif</div></article>@empty<div class="review-empty"><i class="bi bi-chat-square-heart"></i><h2>এখনও কোনো রিভিউ নেই</h2><p>প্রথম রিভিউটি আপনি দিতে পারেন।</p></div>@endforelse</div></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@if ($related->isNotEmpty())<section class="section products-section"><div class="container"><div class="section-head"><h2>আপনার আরও ভালো লাগতে পারে</h2></div><div class="row g-4">@foreach ($related as $item)<div class="col-6 col-lg-3"><x-product-card :product="$item" /></div>@endforeach</div></div></section>@endif
@endsection
