<?php

use App\Http\Controllers\Admin\BrandController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\OrderListController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\SettingsController;
use App\Http\Controllers\Admin\SubcategoryController;
use App\Http\Controllers\Admin\SupportTicketController;
use App\Http\Controllers\Admin\TrackingController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\AuthenticatedSessionController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\CustomerAccountController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProductReviewController;
use App\Http\Controllers\StoreController;
use App\Http\Controllers\TrackingEventController;
use Illuminate\Support\Facades\Route;

Route::get('/', [StoreController::class, 'home'])->name('home');
Route::get('/shop', [StoreController::class, 'shop'])->name('shop');
Route::get('/contact', [StoreController::class, 'contact'])->name('contact');
Route::get('/chair/{product:slug}', [StoreController::class, 'product'])->name('product');
Route::post('/chair/{product:slug}/reviews', [ProductReviewController::class, 'store'])->middleware('throttle:30,1,reviews:')->name('product.reviews.store');
Route::get('/cart', [CartController::class, 'index'])->name('cart');
Route::post('/cart/{product}/add', [CartController::class, 'add'])->name('cart.add');
Route::patch('/cart/{product}', [CartController::class, 'update'])->name('cart.update');
Route::delete('/cart/{product}', [CartController::class, 'remove'])->name('cart.remove');
Route::get('/checkout', [CheckoutController::class, 'index'])->name('checkout');
Route::post('/checkout/coupon', [CheckoutController::class, 'applyCoupon'])->middleware('throttle:20,1,coupon:')->name('checkout.coupon.apply');
Route::delete('/checkout/coupon', [CheckoutController::class, 'removeCoupon'])->name('checkout.coupon.remove');
Route::post('/checkout', [CheckoutController::class, 'store'])->name('checkout.store')->middleware('throttle:checkout')->block(30, 30);
Route::post('/checkout/incomplete', [CheckoutController::class, 'saveIncomplete'])->name('checkout.incomplete.store')->middleware('throttle:60,1,incomplete:')->block(30, 30);
Route::get('/order/{order}/success', [CheckoutController::class, 'success'])->name('order.success');
Route::get('/dashboard', DashboardController::class)->name('dashboard');
Route::get('/refer/{code}', [CustomerAccountController::class, 'referral'])->middleware('throttle:30,1,referral:')->name('customer.referral');
Route::prefix('account')->name('customer.')->middleware('throttle:60,1,account:')->group(function () {
    Route::get('/orders/{order}/invoice', [DashboardController::class, 'invoice'])->name('orders.invoice');
    Route::put('/profile', [CustomerAccountController::class, 'profile'])->name('profile');
    Route::put('/password', [CustomerAccountController::class, 'password'])->middleware(['auth', 'throttle:6,1,customer-password:'])->name('password');
    Route::post('/wishlist/{product}', [CustomerAccountController::class, 'wishlist'])->name('wishlist.add');
    Route::delete('/wishlist/{product}', [CustomerAccountController::class, 'wishlist'])->name('wishlist.remove');
    Route::post('/addresses', [CustomerAccountController::class, 'address'])->name('addresses.save');
    Route::delete('/addresses/{address}', [CustomerAccountController::class, 'deleteAddress'])->name('addresses.remove');
    Route::post('/tickets', [CustomerAccountController::class, 'ticket'])->middleware('throttle:10,1,tickets:')->name('tickets.store');
    Route::post('/tickets/{ticket}/reply', [CustomerAccountController::class, 'reply'])->name('tickets.reply');
    Route::post('/inbox/read', [CustomerAccountController::class, 'readInbox'])->name('inbox.read');
});
Route::match(['get', 'post'], '/track', [StoreController::class, 'track'])->name('track');
Route::get('/info/{slug}', [StoreController::class, 'page'])->name('page');
Route::post('/tracking/events', TrackingEventController::class)->middleware('throttle:120,1,tracking:')->name('tracking.events');
Route::middleware('guest')->group(function () {
    Route::get('/login', [AuthenticatedSessionController::class, 'create'])->name('login');
    Route::post('/login', [AuthenticatedSessionController::class, 'store'])->middleware('throttle:login');
});
Route::middleware('auth')->group(function () {
    Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])->name('logout');
    Route::middleware('admin')->group(function () {
        Route::get('/admin/support', [SupportTicketController::class, 'index'])->name('admin.support.index');
        Route::get('/admin/support/today', [SupportTicketController::class, 'today'])->name('admin.support.today');
        Route::patch('/admin/support/{ticket}', [SupportTicketController::class, 'update'])->name('admin.support.update');
        Route::delete('/admin/support/{ticket}', [SupportTicketController::class, 'destroy'])->name('admin.support.destroy');
        Route::get('/admin', [AdminController::class, 'index'])->name('admin');
        Route::get('/admin/categories', [CategoryController::class, 'index'])->name('admin.categories.index');
        Route::post('/admin/categories', [CategoryController::class, 'store'])->name('admin.categories.store');
        Route::put('/admin/categories/{category}', [CategoryController::class, 'update'])->name('admin.categories.update');
        Route::patch('/admin/categories/{category}/toggle', [CategoryController::class, 'toggle'])->name('admin.categories.toggle');
        Route::delete('/admin/categories/{category}', [CategoryController::class, 'destroy'])->name('admin.categories.destroy');
        Route::get('/admin/subcategories', [SubcategoryController::class, 'index'])->name('admin.subcategories.index');
        Route::post('/admin/subcategories', [SubcategoryController::class, 'store'])->name('admin.subcategories.store');
        Route::get('/admin/brands', [BrandController::class, 'index'])->name('admin.brands.index');
        Route::post('/admin/brands', [BrandController::class, 'store'])->name('admin.brands.store');
        Route::get('/admin/products', [ProductController::class, 'index'])->name('admin.products.index');
        Route::get('/admin/products/create', [ProductController::class, 'create'])->name('admin.products.create');
        Route::post('/admin/products', [ProductController::class, 'store'])->name('admin.products.store');
        Route::get('/admin/products/low-stock', [ProductController::class, 'index'])->name('admin.products.low-stock');
        Route::get('/admin/products/sale', [ProductController::class, 'index'])->name('admin.products.sale');
        Route::get('/admin/products/{product}/edit', [ProductController::class, 'edit'])->name('admin.products.edit');
        Route::put('/admin/products/{product}', [ProductController::class, 'update'])->name('admin.products.update');
        Route::patch('/admin/products/{product}/toggle', [ProductController::class, 'toggle'])->name('admin.products.toggle');
        Route::delete('/admin/products/{product}', [ProductController::class, 'destroy'])->name('admin.products.destroy');
        Route::get('/admin/orders/{filter?}', [OrderListController::class, 'index'])->whereIn('filter', ['new', 'processing', 'shipping', 'completed', 'cancelled'])->name('admin.orders.index');
        Route::patch('/admin/orders/{order}', [AdminController::class, 'update'])->whereNumber('order')->name('admin.order');
        Route::get('/admin/orders/{order}/edit', [OrderListController::class, 'edit'])->whereNumber('order')->name('admin.orders.edit');
        Route::put('/admin/orders/{order}', [OrderListController::class, 'update'])->whereNumber('order')->name('admin.orders.update');
        Route::delete('/admin/orders/{order}', [OrderListController::class, 'destroy'])->whereNumber('order')->name('admin.orders.destroy');
        Route::get('/admin/incomplete-orders', [OrderListController::class, 'incomplete'])->name('admin.incomplete-orders.index');
        Route::get('/admin/incomplete-orders/today', [OrderListController::class, 'incompleteToday'])->name('admin.incomplete-orders.today');
        Route::delete('/admin/incomplete-orders/{incompleteOrder}', [OrderListController::class, 'destroyIncomplete'])->name('admin.incomplete-orders.destroy');
        Route::get('/admin/fake-orders', [OrderListController::class, 'fake'])->name('admin.fake-orders.index');
        Route::get('/admin/fake-orders/today', [OrderListController::class, 'fakeToday'])->name('admin.fake-orders.today');
        Route::get('/admin/fake-orders/create', [OrderListController::class, 'createFake'])->name('admin.fake-orders.create');
        Route::post('/admin/fake-orders', [OrderListController::class, 'storeFake'])->name('admin.fake-orders.store');
        Route::delete('/admin/fake-orders/{order}', [OrderListController::class, 'destroyFake'])->name('admin.fake-orders.destroy');
        Route::get('/admin/tracking', [TrackingController::class, 'index'])->name('admin.tracking');
        Route::put('/admin/tracking', [TrackingController::class, 'update'])->name('admin.tracking.update');
        Route::get('/admin/tracking/{integration}', [TrackingController::class, 'show'])->whereIn('integration', ['meta', 'google', 'tiktok', 'other'])->name('admin.tracking.integration');
        Route::put('/admin/tracking/{integration}', [TrackingController::class, 'updateIntegration'])->whereIn('integration', ['meta', 'google', 'tiktok', 'other'])->name('admin.tracking.integration.update');
        Route::get('/admin/settings', [SettingsController::class, 'general'])->name('admin.settings.general');
        Route::put('/admin/settings', [SettingsController::class, 'updateGeneral'])->name('admin.settings.general.update');
        Route::get('/admin/settings/site', [SettingsController::class, 'site'])->name('admin.settings.site');
        Route::put('/admin/settings/site/{page}/{section}', [SettingsController::class, 'updateSite'])->where(['page' => '[a-z_]+', 'section' => '[a-z0-9_]+'])->name('admin.settings.site.update');
        Route::get('/admin/settings/users/create', [UserController::class, 'create'])->name('admin.settings.users.create');
        Route::post('/admin/settings/users', [UserController::class, 'store'])->name('admin.settings.users.store');
        Route::get('/admin/settings/users/{user}/edit', [UserController::class, 'edit'])->name('admin.settings.users.edit');
        Route::delete('/admin/settings/users/{user}', [UserController::class, 'destroy'])->name('admin.settings.users.destroy');
        Route::put('/admin/settings/users/{user}', [UserController::class, 'update'])->name('admin.settings.users.update');
        Route::get('/admin/settings/users', [SettingsController::class, 'users'])->name('admin.settings.users');
        Route::get('/admin/settings/profile', [SettingsController::class, 'profile'])->name('admin.settings.profile');
        Route::put('/admin/settings/profile', [SettingsController::class, 'updateProfile'])->name('admin.settings.profile.update');
        Route::put('/admin/settings/password', [SettingsController::class, 'updatePassword'])->middleware('throttle:6,1,admin-password:')->name('admin.settings.password.update');
    });
});
